### PR TITLE
Update for newer iosSnapshot frameworks

### PR DESCRIPTION
**Pull request by wesj**
I wanted to use the newest iOSSnapshotTest release, but we've still got Specta tests around relying on this. Would you take an update?

Cocopods with iOSSanpshotTest as a static framework has some issues :(

### CODE REVIEW

**Comment by dblock** [comment]
Yes please! Happy to merge on a passing build. Could also use a new maintainer, haven't written any iOS code in ages.

**Comment by dblock** [comment]
Ugh it tries to clone all of cocoapods?!

**Comment by wesj** [comment]
Oops. I've been running 'pod install' locally instead of 'bundle exec pod install' and running into a bunch of new CocoaPod bugs I didn't need to care about. This seems simpler.

**Comment by dblock** [comment]
@wesj neither @orta or @1aurabrown or i are actively working oh this anymore, want to help out with (co)maintenance? maybe a release?

**Comment by wesj** [comment]
Sure! I'm not a huge Specta user or anything though. Just used in some legacy tests at work :)

**Comment by dblock** [comment]
@wesj Invited you to the project. What's your email so I can `pod trunk add-owner "Expecta+Snapshots" <email>`?

**Comment by dblock** [comment]
I forgot to ask a line in https://github.com/dblock/ios-snapshot-test-case-expecta/blob/master/CHANGELOG.md. We should add danger-changelog too ...

**Comment by wesj** [comment]
Email is wjohnston2000@gmail.com. I'll add a changelog PR :) Thanks

**Comment by dblock** [comment]
> Email is [wjohnston2000@gmail.com](mailto:wjohnston2000@gmail.com). I'll add a changelog PR :) Thanks

Looks like you need to https://guides.cocoapods.org/making/getting-setup-with-trunk.html first.

**Comment by wesj** [comment]
Added. Thanks.

**Comment by dblock** [comment]
Added you to the pod. Party on. See https://github.com/dblock/ios-snapshot-test-case-expecta/blob/master/RELEASING.md if you want to make a release.

**Pull request merged**
