### PR TITLE
Searching for reference images folder in reverse

### LINKED ISSUE #39: Figuring out the tests folder should search closest folders first?
The code for searching the reference images folder searches the path starts from `/`: https://github.com/dblock/ios-snapshot-test-case-expecta/blob/master/EXPMatchers%2BFBSnapshotTest.m#L83

This could be dangerous since we shouldn't really make any guarantees about the whole directory structure. IMO, we should search using `[pathComponents reverseObjectEnumerator]`. However, this might break existing projects 🙈 

One could use `setGlobalReferenceImageDir` to avoid this, but having to do it on every test file seems not practical.

### PR DESCRIPTION
**Pull request by marcelofabri**
Fixes #39

### CODE REVIEW

**Comment by orta** [comment]
Took a quick look:
```
Test Case '-[ARAnimatedTickViewSpec test_initWithSelection__inits_with_selected]' started.
Printing description of pathComponents:
<__NSArrayM 0x7f88b2c0e190>(
/,
Users,
orta,
dev,
ios,
eigen,
Artsy_Tests,
View_Tests,
ARAnimatedTickViewTest.m
)
```

Definitely agree with this PR, don't consider it a breaking change either.  Good move.

**Comment by orta** [comment]
Wait, this very literally will break see my example, can you make it check for existence of the reference Images dir, and then continue if not?

**Comment by marcelofabri** [comment]
Yep, I thought this might break existing setups. Checking the existence of the folder is smart, but that won't work if you're creating it for the first time. 

Maybe we should search for a folder that contains the reference dir first and if not found just use the first one found (as in this PR).

**Comment by marcelofabri** [comment]
I've updated the PR with this approach ^^^

**Comment by orta** [comment]
Perfect, this looks good @marcelofabri - thanks!

**Pull request merged**
