### PR TITLE
Switch to #if __has_include.

### LINKED ISSUE #17: switch to #if __has_include
`#if __has_include(<FacebookSDK/FacebookSDK.h>)`

CocoaPods will be dropping support for he old `COCOAPODS_POD_AVAILABLE` defines.

### PR DESCRIPTION
**Pull request by ruslanskorb**
Hi guys!

Thank you for the cool library!
A little help from me :-]

Fixes #17.

### CODE REVIEW

**Comment by orta** [comment]
awwwwweeesssome

**Comment by orta** [comment]
Thanks, merging.

**Comment by ruslanskorb** [comment]
@orta :thumbsup:
Can you please add minor pod release for this?

**Comment by orta** [comment]
sure, done

**Comment by ruslanskorb** [comment]
Thanks a lot!

**Comment by ruslanskorb** [comment]
Unfortunately, it seems that this fix is not included in the version 1.3.3 - https://github.com/dblock/ios-snapshot-test-case-expecta/compare/1.3.3...master.

**Pull request merged**
