### PR TITLE
Flaky tests on i386 simulator devices

### PR DESCRIPTION
**Pull request by dragvs**
Have simple fix but it's hard to test because it's needed to obtain UIView instance with 256-bytes aligned pointer value.

Simulators affected by this issue: iPad 2, iPad Retina, iPhone 4s, iPhone 5.

### CODE REVIEW

**Comment by dblock** [comment]
I would merge if build passed. I realized it may be an unrelated failure, but I haven't touched this project in a bit and could use some help.

**Comment by dragvs** [comment]
Trying to fix this build failure. It could be because of the outdated cocoapods master repo on a Travis build worker. The latest successful build on Travis was 8 month ago (June 2016), things have been changed with CocoaPods (no more 'repo update' on 'pod install') and with Travis.

**Comment by orta** [comment]
Looks good ( it's now green )

**Pull request merged**
